# Generated by Django 2.0.2 on 2018-04-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryuser',
            name='activation_code',
            field=models.TextField(default='null'),
        ),
    ]
